### ISSUE TITLE
无法下载插件

### ISSUE THREAD

**Issue by kashiori** [slime7/kanmand#1]
![image](https://user-images.githubusercontent.com/38599680/58551414-e7d1fc00-824a-11e9-86b6-b9973223b7c6.png)

**Comment by slime7** [comment]
@kashiori 抱歉，新版本发布的时候用的不是常用那台电脑，没打包进去。
https://github.com/slime7/kanmand/releases/download/v1.0.7/poi-plugin-ghost-1.0.3.tgz
